set nocompatible              " be iMproved, required

execute pathogen#infect()

filetype plugin indent on    " required

syntax on 

set foldmethod=syntax
set tabstop=8
set expandtab
set shiftwidth=4
set autoindent
set smartindent

