set nocompatible              " be iMproved, required

execute pathogen#infect()

filetype plugin indent on    " required

syntax on 
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

" NERDTree toggle key
map <C-n> :NERDTreeToggle<CR>
" minimize windows
map <C-m> <C-W>_   
" Navigation keys
map <C-j> <C-w>j
map <C-K> <C-W>k
map <C-L> <C-W>l
map <C-H> <C-W>h

" Code folding
set foldmethod=syntax
set foldlevel=6 " resonable default fold level 

